// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface ActivitiesBacad2Ba27ARow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  title: string;
  anchor_id: number | null;
  start_time: string | null;
  end_time: string | null;
  status: string | null;
  activity_type: string | null;
  description: string | null;
  viewer_count: number | null;
  duration_minutes: number | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type ActivitiesBacad2Ba27AInsert = Omit<ActivitiesBacad2Ba27ARow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type ActivitiesBacad2Ba27AUpdate = Partial<ActivitiesBacad2Ba27AInsert>;

export interface AnchorsBacad2Ba27ARow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  nickname: string;
  avatar: string | null;
  phone: string | null;
  email: string | null;
  status: string | null;
  level: string | null;
  department: string | null;
  follower_count: number | null;
  bio: string | null;
  anchor_emp_id: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type AnchorsBacad2Ba27AInsert = Omit<AnchorsBacad2Ba27ARow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type AnchorsBacad2Ba27AUpdate = Partial<AnchorsBacad2Ba27AInsert>;

export interface SyncLogsBacad2Ba27ARow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  doc_url: string | null;
  sync_type: string | null;
  status: string | null;
  record_count: number | null;
  error_message: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SyncLogsBacad2Ba27AInsert = Omit<SyncLogsBacad2Ba27ARow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SyncLogsBacad2Ba27AUpdate = Partial<SyncLogsBacad2Ba27AInsert>;

export interface SystemSettingsBacad2Ba27ARow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  setting_key: string;
  setting_value: string | null;
  setting_type: string | null;
  description: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SystemSettingsBacad2Ba27AInsert = Omit<SystemSettingsBacad2Ba27ARow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SystemSettingsBacad2Ba27AUpdate = Partial<SystemSettingsBacad2Ba27AInsert>;
