ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS type VARCHAR(64);
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS index_id VARCHAR(128);
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS model VARCHAR(64);
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS system_prompt TEXT;

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS metadata JSONB;
